title:              Brittany Frederick
email:              brittanyfrederick4990@gmail.com
description:        Data Analyst / Data Scientist
author:             Brittany Frederick
baseurl:            ""
url:                "https://britfred09.github.io"

# Social Profiles
twitter_username:   
github_username:   BritFred09
facebook_username:  
instagram_username:  
linkedin_username:   brittany-frederick-3b994623

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
kramdown:
input: GFM
syntax_highlighter: rouge
